package modules.RegularGrammar.controller;

public enum Actions {
	ADD_ALPHABET, ADD_NON_TERMINAL_VARIABLES, SELECT_INITIAL_AXIOMATIC_SYMBOL, VALIDATE, ADD_PRODUCTION,
	VALIDATE_LANGUAJE, PANEL_PARTIAL_TREE, PANEL_GRAMMAR
}
